# Generated by Django 5.1.4 on 2025-02-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='noofstudents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='noofsubjects',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
