# Generated by Django 5.1.4 on 2025-02-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('regno', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('year', models.CharField(max_length=10)),
                ('scholarshipname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HostelAndMess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostelname', models.CharField(max_length=10)),
                ('Hostelfeespaid', models.BooleanField(default=True)),
                ('messfeespaid', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feespaid', models.BooleanField(default=True)),
                ('feesremaining', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('currentbacklogs', models.PositiveIntegerField(default=0)),
                ('cgpa', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.studentprofile')),
            ],
        ),
    ]
