# Generated by Django 5.1.4 on 2025-02-04 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city')),
            ],
        ),
    ]
