# Generated by Django 5.1.4 on 2025-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='city_field',
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
