# Generated by Django 5.1.4 on 2025-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_college_city_field_city_population_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
